# Generated by Django 3.1.5 on 2021-03-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=100, unique=True)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fund', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20, unique=True)),
                ('counts', models.IntegerField(default=1)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('link', models.TextField()),
                ('content', models.TextField(null=True)),
                ('sch_key', models.CharField(max_length=200)),
                ('public_year', models.CharField(max_length=20)),
                ('source_type', models.CharField(default='', max_length=20)),
                ('local_url', models.CharField(default='', max_length=20)),
                ('cite', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('paper_funds', models.CharField(default='', max_length=200)),
                ('paper_keywords', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(default='', max_length=100, unique=True)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearToKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=0)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.keyword')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.year')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolToKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=0)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.keyword')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.school')),
            ],
        ),
        migrations.CreateModel(
            name='PaperToSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.paper')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.school')),
            ],
        ),
        migrations.CreateModel(
            name='PaperToKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.keyword')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperToAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.author')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.paper')),
            ],
        ),
        migrations.CreateModel(
            name='FundToKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=0)),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.fund')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorToKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=0)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.author')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.keyword')),
            ],
        ),
    ]
