# Generated by Django 3.1.5 on 2021-03-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='source_type',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='paper_funds',
            new_name='funds',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='paper_keywords',
            new_name='keywords',
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='public_year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='sch_key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('title', 'journal')},
        ),
    ]
