# Generated by Django 3.1.5 on 2021-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_auto_20210310_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
