# Generated by Django 2.0.5 on 2019-04-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authortokeyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Keyword', unique=True),
        ),
        migrations.AlterField(
            model_name='fundtokeyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Keyword', unique=True),
        ),
        migrations.AlterField(
            model_name='schooltokeyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Keyword', unique=True),
        ),
        migrations.AlterField(
            model_name='yeartokeyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Keyword', unique=True),
        ),
    ]
